"""Initial schema: tenants, documents, chunks, jobs, and Row Level Security.

Three things here are not produced by autogenerate and are the parts worth
reviewing closely:

1. **The pgvector extension**, created before any table that uses it.
2. **The vector and lexical indexes.** An HNSW index with a cosine operator
   class and a partial predicate, and a GIN index on the tsvector, neither of
   which Alembic can express -- ``migrations/env.py`` excludes them from
   autogenerate so they are not proposed for deletion on every later run.
3. **Row Level Security.** Every tenant table gets a policy keyed on
   ``app.current_org_id``, and FORCE so the table owner is subject to it too.

Revision ID: d189249c1e61
Revises:
Create Date: 2026-09-15 18:18:39.096709+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'd189249c1e61'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: Tables carrying tenant data. Each gets RLS enabled, forced, and a policy.
#: `tests/integration/test_rls.py` enumerates this list against the live
#: database rather than spot-checking, so a table added later without a policy
#: fails the suite instead of leaking quietly.
TENANT_TABLES: tuple[str, ...] = (
    "locations",
    "users",
    "documents",
    "document_versions",
    "chunks",
    "ingestion_jobs",
    "ingestion_job_events",
    "audit_log",
    "conversations",
    "conversation_messages",
)

#: Deliberately outside tenant scoping, with the reason.
GLOBAL_TABLES: dict[str, str] = {
    "organizations": "the tenant roots; policy restricts a session to its own row",
    "embedding_spaces": "vector-space registry; contains no tenant data",
    "user_directory": "minimal email -> organization map, needed to resolve login",
}

#: Reads the tenant from the transaction-local setting. `nullif(..., '')` makes
#: an unset value NULL rather than a cast error, so "no tenant context" denies
#: every row instead of raising -- default-deny is the only safe failure mode.
_TENANT_PREDICATE = (
    "organization_id = nullif(current_setting('app.current_org_id', true), '')::uuid"
)


def upgrade() -> None:
    # pgvector must exist before `chunks` declares a vector column.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_spaces',
    sa.Column('provider_type', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('normalized', sa.Boolean(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embedding_spaces')),
    sa.UniqueConstraint('provider_type', 'model', 'dimension', name=op.f('uq_embedding_spaces_provider_type_model_dimension'))
    )
    op.create_index('uq_embedding_spaces_current', 'embedding_spaces', ['is_current'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('audit_log',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('LOGIN_SUCCESS', 'LOGIN_FAILURE', 'DOCUMENT_UPLOAD', 'DOCUMENT_DELETE', 'VERSION_ACTIVATE', 'VERSION_ROLLBACK', 'VERSION_FAIL', 'TOOL_DENIED', 'CHAT', name='audit_action', native_enum=False, length=40), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_log_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_org_created', 'audit_log', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_organization_id'), 'audit_log', ['organization_id'], unique=False)
    op.create_index('ix_audit_log_resource', 'audit_log', ['resource_type', 'resource_id'], unique=False)
    op.create_table('locations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_locations_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('organization_id', 'slug', name=op.f('uq_locations_organization_id_slug'))
    )
    op.create_index(op.f('ix_locations_organization_id'), 'locations', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='user_role', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_users_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('organization_id', 'email', name=op.f('uq_users_organization_id_email'))
    )
    op.create_index(op.f('ix_users_location_id'), 'users', ['location_id'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('conversations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_conversations_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_conversations_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index('ix_conversations_org_user', 'conversations', ['organization_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_conversations_organization_id'), 'conversations', ['organization_id'], unique=False)
    op.create_table('documents',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('PDF', 'TEXT', 'MARKDOWN', 'HTML', 'CSV', 'WEB', 'API', name='source_type', native_enum=False, length=20), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_documents_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_documents_location_id_locations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_documents_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('organization_id', 'location_id', 'slug', name=op.f('uq_documents_organization_id_location_id_slug'))
    )
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_location_id'), 'documents', ['location_id'], unique=False)
    op.create_index('ix_documents_org_location', 'documents', ['organization_id', 'location_id'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_table('user_directory',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_user_directory_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_directory_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('email', name=op.f('pk_user_directory')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_directory_user_id'))
    )
    op.create_index(op.f('ix_user_directory_organization_id'), 'user_directory', ['organization_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('grounding_ratio', sa.Float(), nullable=True),
    sa.Column('trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_conversation_messages_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_messages'))
    )
    op.create_index('ix_conversation_messages_conv', 'conversation_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_conversation_messages_organization_id'), 'conversation_messages', ['organization_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'ACTIVE', 'INACTIVE', 'FAILED', name='version_status', native_enum=False, length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extraction_mode', sa.Enum('NATIVE', 'OCR', 'HYBRID', name='text_extraction_mode', native_enum=False, length=16), nullable=True),
    sa.Column('ocr_used', sa.Boolean(), nullable=False),
    sa.Column('ocr_page_count', sa.Integer(), nullable=False),
    sa.Column('ocr_mean_confidence', sa.Float(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_versions_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_document_versions_location_id_locations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_document_versions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_document_versions_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    sa.UniqueConstraint('document_id', 'version_number', name=op.f('uq_document_versions_document_id_version_number'))
    )
    op.create_index(op.f('ix_document_versions_checksum_sha256'), 'document_versions', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index('ix_document_versions_org_status', 'document_versions', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_document_versions_organization_id'), 'document_versions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_document_versions_status'), 'document_versions', ['status'], unique=False)
    op.create_index('uq_document_versions_one_active', 'document_versions', ['document_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('chunks',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('PDF', 'TEXT', 'MARKDOWN', 'HTML', 'CSV', 'WEB', 'API', name='source_type', native_enum=False, length=20), nullable=False),
    sa.Column('source_name', sa.String(length=512), nullable=False),
    sa.Column('page_from', sa.Integer(), nullable=True),
    sa.Column('page_to', sa.Integer(), nullable=True),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('section_path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('section_key', sa.String(length=32), nullable=True),
    sa.Column('topic_key', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('embedding_space_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_chunks_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['embedding_space_id'], ['embedding_spaces.id'], name=op.f('fk_chunks_embedding_space_id_embedding_spaces'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_chunks_location_id_locations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_chunks_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks')),
    sa.UniqueConstraint('document_version_id', 'ordinal', name=op.f('uq_chunks_document_version_id_ordinal'))
    )
    op.create_index(op.f('ix_chunks_content_hash'), 'chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_chunks_embedding_space_id'), 'chunks', ['embedding_space_id'], unique=False)
    op.create_index(op.f('ix_chunks_organization_id'), 'chunks', ['organization_id'], unique=False)
    op.create_index('ix_chunks_tenant_active', 'chunks', ['organization_id', 'is_active', 'location_id'], unique=False)
    op.create_index('ix_chunks_topic', 'chunks', ['organization_id', 'topic_key'], unique=False)
    op.create_index('ix_chunks_version', 'chunks', ['document_version_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='job_status', native_enum=False, length=20), nullable=False),
    sa.Column('current_stage', sa.Enum('UPLOADED', 'PARSING', 'OCR', 'CLEANING', 'CHUNKING', 'EMBEDDING', 'INDEXING', 'VALIDATING', 'ACTIVATING', 'COMPLETED', 'FAILED', name='ingestion_stage', native_enum=False, length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_stage', sa.Enum('UPLOADED', 'PARSING', 'OCR', 'CLEANING', 'CHUNKING', 'EMBEDDING', 'INDEXING', 'VALIDATING', 'ACTIVATING', 'COMPLETED', 'FAILED', name='ingestion_stage', native_enum=False, length=20), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_ingestion_jobs_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_ingestion_jobs_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_ingestion_jobs_location_id_locations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ingestion_jobs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_jobs')),
    sa.UniqueConstraint('document_version_id', name=op.f('uq_ingestion_jobs_document_version_id'))
    )
    op.create_index('ix_ingestion_jobs_org_status', 'ingestion_jobs', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_organization_id'), 'ingestion_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_status'), 'ingestion_jobs', ['status'], unique=False)
    op.create_table('ingestion_job_events',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('UPLOADED', 'PARSING', 'OCR', 'CLEANING', 'CHUNKING', 'EMBEDDING', 'INDEXING', 'VALIDATING', 'ACTIVATING', 'COMPLETED', 'FAILED', name='ingestion_stage', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], name=op.f('fk_ingestion_job_events_job_id_ingestion_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ingestion_job_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_job_events'))
    )
    op.create_index('ix_ingestion_job_events_job', 'ingestion_job_events', ['job_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ingestion_job_events_organization_id'), 'ingestion_job_events', ['organization_id'], unique=False)
    # ### end Alembic commands ###

    _create_search_indexes()
    _enable_row_level_security()


def _create_search_indexes() -> None:
    """The two indexes that make hybrid search work.

    The HNSW index is **partial on is_active**. That is deliberate: the graph
    then contains only chunks a query can actually return, so traversal is not
    spent on superseded versions whose rows the filter would discard anyway.
    It also directly mitigates filtered-ANN recall collapse -- see
    docs/hybrid-search.md.
    """
    op.execute(
        """
        CREATE INDEX ix_chunks_embedding_hnsw
            ON chunks USING hnsw (embedding vector_cosine_ops)
            WITH (m = 16, ef_construction = 64)
            WHERE is_active
        """
    )
    # GIN pre-filters correctly, which is why the lexical arm is the recall
    # floor when the ANN arm loses candidates to the tenant predicate.
    op.execute("CREATE INDEX ix_chunks_search_vector ON chunks USING gin (search_vector)")


def _enable_row_level_security() -> None:
    """Install tenant policies.

    FORCE matters as much as ENABLE. Without it a table's owner is exempt from
    its own policies, so a deployment that happened to connect as the owner
    would see every tenant's rows with no error anywhere. The application
    connects as a separate non-owner role (docker/postgres/init.sql), and FORCE
    means the isolation holds even if that is ever misconfigured.
    """
    for table in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
                USING ({_TENANT_PREDICATE})
                WITH CHECK ({_TENANT_PREDICATE})
            """
        )

    # The organizations table keys on its own id rather than organization_id.
    # ENABLE without FORCE: the owner still manages tenants (provisioning,
    # seeding), while the application role sees only its own organization.
    op.execute("ALTER TABLE organizations ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON organizations
            USING (id = nullif(current_setting('app.current_org_id', true), '')::uuid)
        """
    )

    # Grant the application role table access. ALTER DEFAULT PRIVILEGES in
    # init.sql covers this too; doing it explicitly means the migration is
    # correct even against a database that was not bootstrapped by that script.
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_rw') THEN
                GRANT SELECT, INSERT, UPDATE, DELETE
                    ON ALL TABLES IN SCHEMA public TO app_rw;
                GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_rw;
            END IF;
        END
        $$
        """
    )


def downgrade() -> None:
    for table in (*TENANT_TABLES, "organizations"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
    op.execute("DROP INDEX IF EXISTS ix_chunks_search_vector")
    op.execute("DROP INDEX IF EXISTS ix_chunks_embedding_hnsw")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_job_events_organization_id'), table_name='ingestion_job_events')
    op.drop_index('ix_ingestion_job_events_job', table_name='ingestion_job_events')
    op.drop_table('ingestion_job_events')
    op.drop_index(op.f('ix_ingestion_jobs_status'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_organization_id'), table_name='ingestion_jobs')
    op.drop_index('ix_ingestion_jobs_org_status', table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index('ix_chunks_version', table_name='chunks')
    op.drop_index('ix_chunks_topic', table_name='chunks')
    op.drop_index('ix_chunks_tenant_active', table_name='chunks')
    op.drop_index(op.f('ix_chunks_organization_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_embedding_space_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_content_hash'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('uq_document_versions_one_active', table_name='document_versions', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_document_versions_status'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_organization_id'), table_name='document_versions')
    op.drop_index('ix_document_versions_org_status', table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_checksum_sha256'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_conversation_messages_organization_id'), table_name='conversation_messages')
    op.drop_index('ix_conversation_messages_conv', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_user_directory_organization_id'), table_name='user_directory')
    op.drop_table('user_directory')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index('ix_documents_org_location', table_name='documents')
    op.drop_index(op.f('ix_documents_location_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_conversations_organization_id'), table_name='conversations')
    op.drop_index('ix_conversations_org_user', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_location_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_locations_organization_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index('ix_audit_log_resource', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_organization_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_org_created', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('uq_embedding_spaces_current', table_name='embedding_spaces', postgresql_where=sa.text('is_current'))
    op.drop_table('embedding_spaces')
    # ### end Alembic commands ###
